<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE assembly [
        <!ELEMENT assembly (formats|includeBaseDirectory|fileSets|dependencySets|files)*>
        <!ELEMENT formats (format)*>
        <!ELEMENT format (#PCDATA)>
        <!ELEMENT includeBaseDirectory (#PCDATA)>
        <!ELEMENT fileSets (fileSet)*>
        <!ELEMENT fileSet (directory|outputDirectory|excludes|includes|fileMode)*>
        <!ELEMENT directory (#PCDATA)>
        <!ELEMENT outputDirectory (#PCDATA)>
        <!ELEMENT excludes (exclude)*>
        <!ELEMENT exclude (#PCDATA)>
        <!ELEMENT includes (include)*>
        <!ELEMENT include (#PCDATA)>
        <!ELEMENT fileMode (#PCDATA)>
        <!ELEMENT dependencySets (dependencySet)*>
        <!ELEMENT dependencySet (outputDirectory|includes|outputFileNameMapping)*>
        <!ELEMENT outputFileNameMapping (#PCDATA)>
        <!ELEMENT files (file)*>
        <!ELEMENT file (source|outputDirectory|fileMode|destName|filtered)*>
        <!ELEMENT source (#PCDATA)>
        <!ELEMENT destName (#PCDATA)>
        <!ELEMENT filtered (#PCDATA)>
        ]>
<assembly>

    <formats>
        <format>zip</format>
    </formats>
    <includeBaseDirectory>false</includeBaseDirectory>
    <fileSets>
        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}</directory>
            <outputDirectory>wso2ei-${pom.version}</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/repository/conf/**</exclude>
                <exclude>**/repository/components/**</exclude>
                <exclude>**/lib/**</exclude>
                <exclude>**/bin/**</exclude>
                <exclude>**/conf/axis2/axis2.xml</exclude>
                <exclude>**/conf/axis2/tenant-axis2.xml</exclude>
                <exclude>**/conf/synapse.xml</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/services/sample01.aar</exclude>
                <exclude>**/repository/services/version/**</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/repository/components/plugins/saxon*.jar</exclude>
                <exclude>**/lib/endorsed/xalan*.jar</exclude>
                <exclude>**/repository/conf/tomcat/catalina-server.xml</exclude>
                <exclude>**/repository/conf/registry.xml</exclude>
                <exclude>**/repository/conf/tomcat/web.xml</exclude>
                <exclude>**/webapp-mode/WEB-INF/web.xml</exclude>
                <exclude>**/repository/conf/tomcat/carbon/WEB-INF/web.xml</exclude>
		<exclude>**/repository/components/plugins/httpclient_4.3.1.wso2v2.jar</exclude>
		<exclude>**/repository/components/plugins/axis2-transport-jms_1.1.1.wso2v2.jar</exclude>
		<exclude>**/repository/components/plugins/axis2-transport-sms_1.1.1.wso2v2.jar</exclude>
		<exclude>**/repository/components/plugins/axis2-transport-mail_1.1.1.wso2v2.jar</exclude>
		<exclude>**/repository/components/plugins/jsch_0.1.49.wso2v1.jar</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/conf</directory>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/axis2/axis2.xml</exclude>
                <exclude>**/axis2/tenant-axis2.xml</exclude>
                <exclude>**/synapse.xml</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/services/sample01.aar</exclude>
                <exclude>**/repository/services/version/**</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/repository/components/plugins/saxon*.jar</exclude>
                <exclude>**/lib/endorsed/xalan*.jar</exclude>
                <exclude>**//tomcat/catalina-server.xml</exclude>
                <exclude>**//registry.xml</exclude>
                <exclude>**/tomcat/web.xml</exclude>
                <exclude>**/webapp-mode/WEB-INF/web.xml</exclude>
                <exclude>**/tomcat/carbon/WEB-INF/web.xml</exclude>
                <exclude>**/repository/components/plugins/httpclient_4.3.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-jms_1.1.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-sms_1.1.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-mail_1.1.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/jsch_0.1.49.wso2v1.jar</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components</directory>
            <outputDirectory>wso2ei-${pom.version}/wso2/components</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>*dropins/**</exclude>
                <exclude>*patches/**</exclude>
                <exclude>*servicepacks/**</exclude>
                <exclude>*extensions/**</exclude>
                <exclude>*lib/**</exclude>
                <exclude>**/conf/axis2/tenant-axis2.xml</exclude>
                <exclude>**/conf/synapse.xml</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/services/sample01.aar</exclude>
                <exclude>**/repository/services/version/**</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/repository//plugins/saxon*.jar</exclude>
                <exclude>**/lib/endorsed/xalan*.jar</exclude>
                <exclude>**/repository/conf/tomcat/catalina-server.xml</exclude>
                <exclude>**/repository/conf/registry.xml</exclude>
                <exclude>**/repository/conf/tomcat/web.xml</exclude>
                <exclude>**/webapp-mode/WEB-INF/web.xml</exclude>
                <exclude>**/repository/conf/tomcat/carbon/WEB-INF/web.xml</exclude>
                <exclude>**/repository/components/plugins/httpclient_4.3.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-jms_1.1.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-sms_1.1.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-mail_1.1.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/jsch_0.1.49.wso2v1.jar</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components/dropins</directory>
            <outputDirectory>wso2ei-${pom.version}/dropins</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components/lib</directory>
            <outputDirectory>wso2ei-${pom.version}/lib</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components/patches</directory>
            <outputDirectory>wso2ei-${pom.version}/patches</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components/servicepacks</directory>
            <outputDirectory>wso2ei-${pom.version}/servicepacks</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components/extensions</directory>
            <outputDirectory>wso2ei-${pom.version}/extensions</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/bin</directory>
            <outputDirectory>wso2ei-${pom.version}/bin</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/*.bat</exclude>
                <exclude>build.xml</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>src/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/bin</outputDirectory>
            <includes>
                <include>**.sh</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>
        <fileSet>
            <directory>src/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/bin</outputDirectory>
            <includes>
                <include>**.bat</include>
                <include>build.xml</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/lib</directory>
            <outputDirectory>wso2ei-${pom.version}/wso2/lib</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/conf/axis2/axis2.xml</exclude>
                <exclude>**/conf/axis2/tenant-axis2.xml</exclude>
                <exclude>**/conf/synapse.xml</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/services/sample01.aar</exclude>
                <exclude>**/repository/services/version/**</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/repository//plugins/saxon*.jar</exclude>
                <exclude>**/lib/endorsed/xalan*.jar</exclude>
                <exclude>**/repository/conf/tomcat/catalina-server.xml</exclude>
                <exclude>**/repository/conf/registry.xml</exclude>
                <exclude>**/repository/conf/tomcat/web.xml</exclude>
                <exclude>**/webapp-mode/WEB-INF/web.xml</exclude>
                <exclude>**/repository/conf/tomcat/carbon/WEB-INF/web.xml</exclude>
                <exclude>**/repository/components/plugins/httpclient_4.3.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-jms_1.1.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-sms_1.1.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-mail_1.1.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/jsch_0.1.49.wso2v1.jar</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>./src/resources/tomcat</directory>
            <outputDirectory>wso2ei-${pom.version}/conf/tomcat</outputDirectory>
            <includes>
                <include>**/catalina-server.xml</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>./src/resources</directory>
            <outputDirectory>wso2ei-${pom.version}/wso2/lib/endorsed</outputDirectory>
            <includes>
                <include>**/saxon9he.jar</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>./src/resources/reports</directory>
            <outputDirectory>wso2ei-${pom.version}/repository/resources/reports</outputDirectory>
            <includes>
                <include>**/*.jrxml</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>./src/conf</directory>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <includes>
                <include>**/sec.policy</include>
            </includes>
        </fileSet>
<!--        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}</directory>
            <outputDirectory>wso2ei-${pom.version}</outputDirectory>
            <includes>
                <include>**/*.sh</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>-->
 <!--       <fileSet>
            <directory>../../modules/samples/product/services</directory>
            <outputDirectory>wso2ei-${pom.version}/samples/axis2Server/src</outputDirectory>
            <fileMode>644</fileMode>
            <directoryMode>775</directoryMode>
        </fileSet>
        <fileSet>
            <directory>../../modules/samples/product/src/main/resources</directory>
            <outputDirectory>wso2ei-${pom.version}/samples</outputDirectory>
            <includes>
                <include>**/*.pdf</include>
            </includes>
            <fileMode>644</fileMode>
            <directoryMode>775</directoryMode>
        </fileSet>
        <fileSet>
            <directory>../../modules/samples/product/src/main/java</directory>
            <outputDirectory>wso2ei-${pom.version}/samples/axis2Client/src</outputDirectory>
            <excludes>
                <exclude>**/target</exclude>
                <exclude>**/target/**/*</exclude>
            </excludes>
            <fileMode>644</fileMode>
            <directoryMode>775</directoryMode>
        </fileSet>
        <fileSet>
            <directory>../../modules/samples/product/src/main/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/samples/axis2Client</outputDirectory>
            <includes>
                <include>build.xml</include>
            </includes>
            <fileMode>644</fileMode>
            <directoryMode>775</directoryMode>
        </fileSet>
        <fileSet>
            <directory>../../modules/samples/product/src/main/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/bin</outputDirectory>
            <includes>
                <include>wso2ei-samples.sh</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>
        <fileSet>
            <directory>../../modules/samples/product/src/main/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/bin</outputDirectory>
            <includes>
                <include>wso2ei-samples.bat</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>../../modules/samples/product/src/main/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/samples/axis2Server</outputDirectory>
            <includes>
                <include>axis2server.sh</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>
        <fileSet>
            <directory>../../modules/samples/product/src/main/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/samples/axis2Server</outputDirectory>
            <includes>
                <include>axis2server.bat</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>../../modules/samples/product/src/main/conf/synapse</directory>
            <outputDirectory>wso2ei-${pom.version}/repository/samples</outputDirectory>
            <fileMode>644</fileMode>
        </fileSet>-->
        <fileSet>
            <directory>src/conf/synapse-configs</directory>
            <outputDirectory>wso2ei-${pom.version}/repository/deployment/server/synapse-configs</outputDirectory>
            <excludes>
                <exclude>**/empty.txt</exclude>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>src/conf/carbonapps</directory>
            <outputDirectory>wso2ei-${pom.version}/repository/deployment/server/carbonapps</outputDirectory>
            <excludes>
                <exclude>empty.txt</exclude>
            </excludes>
        </fileSet>
        <!-- For analytic data publishing event-publishers and event-streams -->
        <fileSet>
            <directory>../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/eventpublishers</directory>
            <outputDirectory>wso2ei-${pom.version}/repository/deployment/server/eventpublishers</outputDirectory>
        </fileSet>
        <fileSet>
            <directory>../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/eventstreams</directory>
            <outputDirectory>wso2ei-${pom.version}/repository/deployment/server/eventstreams</outputDirectory>
        </fileSet>
        <fileSet>
            <directory>../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/advanced/</directory>
            <outputDirectory>wso2ei-${pom.version}/conf/advanced</outputDirectory>
           </fileSet>
        <fileSet>
            <directory>../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/security</directory>
            <outputDirectory>wso2ei-${pom.version}/conf/security</outputDirectory>
            <includes>
                <include>**/jaas.conf</include>
                <include>**/krb5.conf</include>
            </includes>
        </fileSet>
	 <!--Multitenancy related file -->
        <fileSet>
            <directory>
                ../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/multitenancy/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/conf/multitenancy</outputDirectory>
            <includes>
                <include>**/stratos.xml</include>
                <include>**/multitenancy-packages.xml</include>
                <include>**/usage-throttling-agent-config.xml</include>
                <include>**/cloud-services-desc.xml</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>
                ../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/multitenancy/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/conf</outputDirectory>
            <includes>
                <include>**/tenant-mgt.xml</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/identity</directory>
            <outputDirectory>wso2ei-${pom.version}/dbscripts/identity</outputDirectory>
            <includes>
                <include>**/**.sql</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>../styles/service/src/main/resources/web/styles/css</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/resources/allthemes/Default/admin</outputDirectory>
            <includes>
                <include>**/**.css</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>../styles/service/src/main/resources/web/styles/images</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/resources/allthemes/Default/images</outputDirectory>
            <includes>
                <include>**/**.gif</include>
                <include>**/**.png</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>lib/home</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/webapps/STRATOS_ROOT</outputDirectory>
        </fileSet>
    </fileSets>
    <dependencySets>
        <!-- use the new tool to create a bundles -->
        <dependencySet>
            <outputDirectory>wso2ei-${pom.version}/wso2/lib/core/WEB-INF/lib</outputDirectory>
            <includes>
                <include>org.wso2.carbon:org.wso2.carbon.mediator.bridge:jar</include>
            </includes>
        </dependencySet>
<!--        <dependencySet>
            <outputDirectory>wso2ei-${pom.version}/samples/axis2Client/client_repo/modules</outputDirectory>
            <includes>
                <include>org.apache.axis2:addressing:mar</include>
                <include>org.apache.rampart:rampart:mar</include>
                <include>org.apache.sandesha2:sandesha2:mar</include>
            </includes>
            <outputFileNameMapping>${artifact.artifactId}.${artifact.extension}</outputFileNameMapping>
        </dependencySet>
        <dependencySet>
            <outputDirectory>wso2ei-${pom.version}/samples/axis2Server/repository/modules</outputDirectory>
            <includes>
                <include>org.apache.axis2:addressing:mar</include>
                <include>org.apache.rampart:rampart:mar</include>
                <include>org.apache.sandesha2:sandesha2:mar</include>
            </includes>
            <outputFileNameMapping>${artifact.artifactId}.${artifact.extension}</outputFileNameMapping>
        </dependencySet>-->
        <dependencySet>
            <outputDirectory>wso2ei-${pom.version}/repository/axis2/client/lib</outputDirectory>
            <includes>
                <include>org.bouncycastle:bcprov-jdk15on:jar</include>
            </includes>
            <outputFileNameMapping>${artifact.artifactId}.${artifact.extension}</outputFileNameMapping>
        </dependencySet>
        <dependencySet>
            <outputDirectory>wso2ei-${pom.version}/repository/deployment/client/modules</outputDirectory>
            <includes>
                <include>org.apache.rampart:rampart:mar</include>
            </includes>
        </dependencySet>
        <dependencySet>
            <outputDirectory>wso2ei-${pom.version}/wso2/lib</outputDirectory>
            <includes>
                <include>org.apache.sandesha2:sandesha2-core:jar</include>
            </includes>
        </dependencySet>
    </dependencySets>

    <files>
	    <file>
            <source>../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/event-broker.xml</source>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/data-bridge/data-agent-config.xml</source>
            <outputDirectory>wso2ei-${pom.version}/conf/data-bridge</outputDirectory>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/axis2.xml</source>
            <outputDirectory>wso2ei-${pom.version}/conf/axis2</outputDirectory>
            <destName>axis2.xml</destName>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/registry.xml</source>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <destName>registry.xml</destName>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/web.xml</source>
            <outputDirectory>wso2ei-${pom.version}/conf/tomcat</outputDirectory>
            <destName>web.xml</destName>
        </file>
        <file>
            <source>src/conf/carbon/web.xml</source>
            <outputDirectory>wso2ei-${pom.version}/conf/tomcat/carbon/WEB-INF</outputDirectory>
            <destName>web.xml</destName>
        </file>
        <file>
            <source>src/conf/webapp-mode/web.xml</source>
            <outputDirectory>wso2ei-${pom.version}/webapp-mode/WEB-INF</outputDirectory>
            <destName>web.xml</destName>
        </file>
        <file>
            <source>src/conf/tenant-axis2.xml</source>
            <outputDirectory>wso2ei-${pom.version}/conf/axis2</outputDirectory>
            <destName>tenant-axis2.xml</destName>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/axis2_nhttp.xml</source>
            <outputDirectory>wso2ei-${pom.version}/conf/axis2</outputDirectory>
            <destName>axis2_nhttp.xml</destName>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/axis2_pt.xml</source>
            <outputDirectory>wso2ei-${pom.version}/conf/axis2</outputDirectory>
            <destName>axis2_pt.xml</destName>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/axis2_blocking_client.xml</source>
            <outputDirectory>wso2ei-${pom.version}/conf/axis2</outputDirectory>
            <destName>axis2_blocking_client.xml</destName>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/log4j.properties</source>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <destName>log4j.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/synapse.properties</source>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <destName>synapse.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/synapse-handlers.xml</source>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <destName>synapse-handlers.xml</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/datasources.properties</source>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <destName>datasources.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/cipher-text.properties</source>
            <outputDirectory>wso2ei-${pom.version}/wso2/lib</outputDirectory>
            <destName>cipher-text.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
         <!-- Cipher Tool Files -->
        <file>
            <source>../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/lib/org.wso2.ciphertool-${cipher.tool.version}.jar</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/wso2/lib</outputDirectory>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/security/cipher-text.properties</source>
            <outputDirectory>wso2ei-${pom.version}/conf/security</outputDirectory>
            <destName>cipher-text.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/security/cipher-tool.properties</source>
            <outputDirectory>wso2ei-${pom.version}/conf/security</outputDirectory>
            <destName>cipher-tool.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/security/secret-conf.properties</source>
            <outputDirectory>wso2ei-${pom.version}/conf/security</outputDirectory>
            <destName>secret-conf.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/nhttp.properties</source>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <destName>nhttp.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/passthru-http.properties</source>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <destName>passthru-http.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/hl7.properties</source>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <destName>hl7.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>             
        <file>
            <source>src/conf/access-log.properties</source>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <destName>access-log.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>               
        <file>
            <source>src/conf/jndi.properties</source>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <destName>jndi.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/rule-engine-config.xml</source>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>